apps/front/models.py
from exts import db
import shortuuid
from werkzeug.security import generate_password_hash,check_password_hash
import enum
from datetime import datetime


"""
(my_env) $ pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple shortuuid
"""


# pip install shortuuid

class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4

class FrontUser(db.Model):
    __tablename__ = 'front_user'
    id = db.Column(db.String(100),primary_key=True,default=shortuuid.uuid)
    telephone = db.Column(db.String(11),nullable=False,unique=True)
    username = db.Column(db.String(50),nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50),unique=True)
    realname = db.Column(db.String(50))
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum),default=GenderEnum.UNKNOW)
    join_time = db.Column(db.DateTime,default=datetime.now)

    def __init__(self,*args,**kwargs):
        if "password" in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop("password")
        super(FrontUser, self).__init__(*args,**kwargs)


    @property
    def password(self):
        return self._password

    @password.setter
    def password(self,newpwd):
        self._password = generate_password_hash(newpwd)

    def check_password(self,rawpwd):
        return check_password_hash(self._password,rawpwd)



#150讲

apps/front/forms.py
from apps.forms import BaseForm
from wtforms import StringField
from wtforms.validators import regexp,InputRequired,EqualTo,ValidationError,Regexp
import hashlib
from utils import zlcache



class SMSCaptchaForm(BaseForm):
    salt = 'q3423805gdflvbdfvhsdoa`#$%'#盐是随便给的
    telephone = StringField(validators=[regexp(r'1[345789]\d{9}')])
    timestamp = StringField(validators=[regexp(r'\d{13}')])
    sign = StringField(validators=[InputRequired()])#Md5值

    def validate(self):
        result = super(SMSCaptchaForm, self).validate()
        if not result:
            return False

        telephone = self.telephone.data
        timestamp = self.timestamp.data
        sign = self.sign.data

        # md5(timestamp+telphone+salt)
        # md5函数必须要传一个bytes类型的字符串进去
        sign2 = hashlib.md5((timestamp + telephone + self.salt).encode('utf-8')).hexdigest()
        print('客户端提交的sign：', sign)
        print('服务器生成的sign：', sign2)
        if sign == sign2:
            return True
        else:
            return False


"""
这上边全是
158讲讲的
下边是161讲
"""
class SignupForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}",message='请输入正确格式的手机号码！')])
    sms_captcha = StringField(validators=[Regexp(r"\w{4}",message='请输入正确格式的短信验证码！')])
    username = StringField(validators=[Regexp(r".{2,20}",message='请输入正确格式的用户名！')])
    password1 = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}",message='请输入正确格式的密码！')])
    password2 = StringField(validators=[EqualTo("password1",message='两次输入的密码不一致！')])
    graph_captcha = StringField(validators=[Regexp(r"\w{4}",message='请输入正确格式的短信验证码！')])

    def validate_sms_captcha(self,field):
        sms_captcha = field.data
        telephone = self.telephone.data
        #
        # sms_captcha_mem = zlcache.get(telephone)
        # if not sms_captcha_mem or sms_captcha_mem.lower() != sms_captcha.lower():
        #     raise ValidationError(message='短信验证码错误！')
        if sms_captcha != '1111':
            sms_captcha_mem = zlcache.get(telephone)
            if not sms_captcha_mem or sms_captcha_mem.lower() != sms_captcha.lower():
                raise ValidationError(message='短信验证码错误！')


    def validate_graph_captcha(self,field):
        graph_captcha = field.data

        # graph_captcha_mem = zlcache.get(graph_captcha.lower())
        # if not graph_captcha_mem:
        #     raise ValidationError(message='图形验证码错误！')
        if graph_captcha != '1111':#这是自己写的测试代码,上面也是,这里这么写是因为真正的注册需要一个真正的手机号码来注册，比较麻烦
            graph_captcha_mem = zlcache.get(graph_captcha.lower())
            if not graph_captcha_mem:
                raise ValidationError(message='图形验证码错误！')

class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}", message='请输入正确格式的手机号码！')])
    password = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message='请输入正确格式的密码！')])
    remeber = StringField()

apps/common/views.py
from flask import  Blueprint

bp = Blueprint("common",__name__,url_prefix='/common')

@bp.route('/')
def index():
    return 'common  index'

apps/front/__init__.py
from .views import bp

apps/front/views.py
from flask import (
    Blueprint,
    views,
    render_template,
    make_response,
    Response,
    Flask,
    request,
session,
url_for

)
from utils.captcha import Captcha
from io import BytesIO
from PIL import Image, ImageFont, ImageDraw
from utils.CCPSDK import CCPRestSDK
from utils import restful,zlcache,safeutils
import config
from .forms import SMSCaptchaForm,SignupForm,SigninForm
from .models import FrontUser

from exts import db
import config

bp = Blueprint("front", __name__)  # url_prefix='cms'表示一个前缀,这里不需要


@bp.route('/')
def index():
    return render_template('front/front_index.html')

@bp.route('/test/')
def front_test():
    return render_template('front/front_test.html')


@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    #存储图形验证码到服务器
    zlcache.set(text.lower(),text.lower())

    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    # print(resp)
    # resp = Response(resp,mimetype="image/png")
    # resp.context_type = 'image/png'
    resp.headers['Content-Type'] = 'image/jpg'

    return resp

# @bp.route('/sms_captcha/')
# def sms_captcha():
#     telephone=request.args.get('telephone')
#     if not telephone:
#         return restful.params_error(message='请传入手机号码')
#     accountSid = "8a216da86f17653b016f3b4046b218ab"
#     accountToken = "ac156972012a43dab1782f1f89995ac9"
#     appId = "8a216da86f17653b016f3b40471818b2"
#     rest = CCPRestSDK.REST(accountSid, accountToken, appId)
#     #下面要有产生随机的验证码函数
#     captcha= Captcha.gene_text(number=4)
#     result = rest.sendTemplateSMS(telephone, [captcha], "1")
#     if result:
#         return restful.success()
#     else:
#         return restful.params_error(message='短信验证码发送失败')

@bp.route('/sms_captcha/',methods=['POST'])
def sms_captcha():
    form = SMSCaptchaForm(request.form)
    if form.validate():
        telephone=form.telephone.data

        accountSid = "8a216da86f17653b016f3b4046b218ab"
        accountToken = "ac156972012a43dab1782f1f89995ac9"
        appId = "8a216da86f17653b016f3b40471818b2"
        rest = CCPRestSDK.REST(accountSid, accountToken, appId)
        captcha = Captcha.gene_text(number=4)
        result = rest.sendTemplateSMS(telephone, [captcha], "1")
        if result:
            #如果发送成功,存储到缓存里面(服务器里面)
            zlcache.set(telephone,captcha)


            return restful.success()
        else:
            return restful.params_error(message='短信验证码发送失败 ')
    else:
        return restful.params_error(message='参数错误')




    # telephone=request.args.get('telephone')
    # if not telephone:
    #     return restful.params_error(message='请传入手机号码')
    # accountSid = "8a216da86f17653b016f3b4046b218ab"
    # accountToken = "ac156972012a43dab1782f1f89995ac9"
    # appId = "8a216da86f17653b016f3b40471818b2"
    # rest = CCPRestSDK.REST(accountSid, accountToken, appId)
    # #下面要有产生随机的验证码函数
    # captcha= Captcha.gene_text(number=4)
    # result = rest.sendTemplateSMS(telephone, [captcha], "1")
    # if result:
    #     return restful.success()
    # else:
    #     return restful.params_error(message='短信验证码发送失败')


#这里是后台代码
class SignupView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html', return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    #结合front/forms.py
    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            print(form.get_error())
            return restful.params_error(message=form.get_error())

##155课时(没有按照flask的来)，这里是测试代码
class SMSCodeView(views.MethodView):
    def get(self):
        #/smscode?tel=xxxxx
        telephone = request.args.get("tel")
        # telephone = request.values.get("tel")
        accountSid="8a216da86f17653b016f3b4046b218ab"
        accountToken = "ac156972012a43dab1782f1f89995ac9"
        appId ="8a216da86f17653b016f3b40471818b2"
        rest = CCPRestSDK.REST(accountSid,accountToken,appId)
        captcha = Captcha.gene_text(number=4)
        result = rest.sendTemplateSMS(telephone, [captcha], "1")
        # result= rest.sendTemplateSMS(telephone,["1234"],"1")
        print(result)
        return Response("success")



class SigninView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for("front.signup") and safeutils.is_safe_url(
                return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    #post方法这里一般需要表单验证,这里代码在front/forms.py里面
    #这是登陆的后台代码
    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remeber.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID]=user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return  restful.params_error(message='手机号或者密码错误')
        else:
            return restful.params_error(message=form.get_error())




bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SigninView.as_view('signin'))

bp.add_url_rule('/smscode/',view_func=SMSCodeView.as_view('smscode'))

templates/front/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include "common/_heads.html" %}

    <title>
        {% block title %}{% endblock %}
    </title>
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">学习论坛</a>
            {#            这里改过#}
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>
                {#                <li><a href="#">Link</a></li>#}
                {#                <li class="dropdown">#}
                {#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
                {#                       aria-expanded="false">Dropdown <span class="caret"></span></a>#}
                {#                    <ul class="dropdown-menu">#}
                {#                        <li><a href="#">Action</a></li>#}
                {#                        <li><a href="#">Another action</a></li>#}
                {#                        <li><a href="#">Something else here</a></li>#}
                {#                        <li role="separator" class="divider"></li>#}
                {#                        <li><a href="#">Separated link</a></li>#}
                {#                        <li role="separator" class="divider"></li>#}
                {#                        <li><a href="#">One more separated link</a></li>#}
                {#                    </ul>#}
                {#                </li>#}
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="请输入关键字(Search)">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('front.signin') }}">登陆</a></li>
                <li><a href="{{ url_for('front.signup') }}">注册</a></li>

                {#                <li class="dropdown">#}
                {#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
                {#                       aria-expanded="false">Dropdown <span class="caret"></span></a>#}
                {#                    <ul class="dropdown-menu">#}
                {#                        <li><a href="#">Action</a></li>#}
                {#                        <li><a href="#">Another action</a></li>#}
                {#                        <li><a href="#">Something else here</a></li>#}
                {#                        <li role="separator" class="divider"></li>#}
                {#                        <li><a href="#">Separated link</a></li>#}
                {#                    </ul>#}
                {#                </li>#}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{% block body %}{% endblock %}
</body>
</html>

templates/front/front_index.html
{% extends "front/front_base.html" %}
{#{% from "common/_macros.html" import static %}#}

{% block title %}学习论坛{% endblock %}



{% block head %}
{#    <link rel="stylesheet" href="{{ static("front/css/front_index.css") }}">#}
{% endblock %}


{% block body %}
    我是首页
{% endblock %}

templates/front/front_signbase.html
{% from 'common/_macros.html' import static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %} {% endblock %}</title>
     <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>

    <script src="{{ static('common/zlparam.js') }}"></script>
     <script src="{{ static("common/zlajax.js") }}"></script>

 <link rel="stylesheet" href="{{ static("common/sweetalert/sweetalert.css") }}">

    <script src="{{ static("common/sweetalert/sweetalert.min.js")}}"></script>
    <script src="{{ static("common/sweetalert/zlalert.js")}}"></script>
    <link rel="stylesheet" href="{{ static('front/css/front_signbase.css')}}">

    {% block  head %}

    {% endblock %}


</head>
<body>
<div class="outer-box">
<div class="logo-box">
    <a href="/">
        <img src="{{ static('common/images/h.png') }}" alt="">
    </a>
</div>
    <h2 class="page-title">
        {% block h2_block %}{% endblock %}
    </h2>
    <div class="sign-box">
{#        <div class="form-group">#}
{#           <div class="input-group">#}
{#                <input type="text" class="form-control"#}
{#            name="telephone" placeholder="手机号码">#}
{#               <span class="input-group-btn">#}
{#                   <button id="sms-captcha-btn" class="btn btn-default">发送验证码</button>#}
{#               </span>#}
{#           </div>#}
{##}
{#        </div>#}
{#         <div class="form-group">#}
{#        <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">#}
{#     </div>#}
{#    <div class="form-group">#}
{#        <input type="text" class="form-control" name="username" placeholder="用户名">#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <input type="password" class="form-control" name="password1" placeholder="密码">#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <input type="password" class="form-control" name="password2" placeholder="确认密码">#}
{#    </div>#}
{##}
{##}
{#<div class="form-group">#}
{#        <div class="input-group">#}
{#            <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码">#}
{#            <span class="input-group-addon captcha-addon">#}
{#                <img id="captcha-img" class="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt="">#}
{#                <img id='captcha-img' class="captcha-img" src="{{ url_for('front.graph_captcha') }}" alt="">#}
{#            </span>#}
{#        </div>#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <span style="display: none;"id="return-to-span">{{ return_to }}</span>#}
{#        <button  id="submit-btn"  class="btn btn-warning btn-block" id="submit-btn">立即注册</button>#}
{#    </div>#}

{% block signbox %}{% endblock %}

    </div>
        <span style="display: none;" id="return-to-span">{{ return_to }}</span>

</div>
</body>
</html>

templates/front/front_signin.html
{% extends 'front/front_signbase.html' %}
{% from "common/_macros.html" import static %}

{% block title %}
    论坛登录
{% endblock %}

{% block head %}
    <script src="{{ static("front/js/front_signin.js") }}"></script>
{% endblock %}

{% block h2_block %}
    论坛账号登录
{% endblock %}

{% block signbox %}
    <div class="form-group">
        <input type="text" class="form-control" name="telephone" placeholder="手机号码">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="密码">
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="remember" value="1">记住我
        </label>
    </div>
    <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
    </div>
    <div class="form-group">
        <a href="{{ url_for("front.signup") }}" class="signup-link">没有账号？立即注册</a>
        <a href="#" class="resetpwd-link" style="float:right;">找回密码</a>
{#        <a href="#"></a>#}
    </div>
{% endblock %}

templates/front/front_signup.html
{% extends 'front/front_signbase.html' %}

{% from 'common/_macros.html' import static %}
{% block title %}
    论坛注册
{% endblock %}
{% block head %}

    <script src="{{ static('front/js/front_signup.js') }}"></script>
{#    <link rel="stylesheet" href="{{ static('front/css/front_signup.css') }}">#}
{% endblock %}

{% block h2_block %}
    论坛账号注册

{% endblock %}
{% block signbox %}

    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control"
                   name="telephone" placeholder="手机号码">
            <span class="input-group-btn">
                   <button id="sms-captcha-btn" class="btn btn-default">发送验证码</button>
               </span>
        </div>

    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="username" placeholder="用户名">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password1" placeholder="密码">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password2" placeholder="确认密码">
    </div>


    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码">
            <span class="input-group-addon captcha-addon">
{#                <img id="captcha-img" class="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt="">#}
                <img id='captcha-img' class="captcha-img" src="{{ url_for('front.graph_captcha') }}" alt="">
            </span>
        </div>
    </div>
    <div class="form-group">
        <button id="submit-btn" class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
    </div>


{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="csrf-token" content="{{ csrf_token() }}">#}
{##}
{#    <title>论坛注册</title>#}
{#     <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>#}
{#    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">#}
{#    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
{#        <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>#}
{##}
{#    <script src="{{ static('common/zlparam.js') }}"></script>#}
{#     <script src="{{ static("common/zlajax.js") }}"></script>#}
{##}
{# <link rel="stylesheet" href="{{ static("common/sweetalert/sweetalert.css") }}">#}
{##}
{#    <script src="{{ static("common/sweetalert/sweetalert.min.js")}}"></script>#}
{#    <script src="{{ static("common/sweetalert/zlalert.js")}}"></script>#}
{##}
{#    <script src="{{ static('front/js/front_signup.js') }}"></script>#}
{#    <link rel="stylesheet" href="{{ static('front/css/front_signup.css') }}">#}
{##}
{#</head>#}

{##}
{#==============================================================================================================================#}
{##}
{##}
{#<body>#}
{#<div class="outer-box">#}
{#<div class="logo-box">#}
{#    <a href="/">#}
{#        <img src="{{ static('common/images/h.png') }}" alt="">#}
{#    </a>#}
{#</div>#}
{#    <h2 class="page-title">账号登陆</h2>#}
{#    <div class="sign-box">#}
{#       #}
{##}
{#    </div>#}
{##}
{#</div>#}
{#</body>#}
{#</html>#}

templates/front/front_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{{ url_for("front.signup") }}">注册</a>

</body>
</html>